Start graceful shutdown on SIGTERM
When the main process recieves SIGTERM or SIGINT, wait
ROUTER_GRACEFUL_SHUTDOWN_DELAY (default: 45) seconds and then signal
the reload script with ROUTER_SHUTDOWN=true that a graceful termination
is requested. The reload-haproxy script then invokes USR1 on the child
processes and waits ROUTER_MAX_SHUTDOWN_TIMEOUT or MAX_RELOAD_WAIT_TIME
(default 30) seconds before invoking TERM on the child processes.
If TERM is invoked the script exits with 1, indicating that not all
processes completed their work.

Clients with long running requests should set ROUTER_MAX_SHUTDOWN_TIMEOUT
as appropriate to ensure all connections exit cleanly.

diff --git a/images/router/haproxy/reload-haproxy b/images/router/haproxy/reload-haproxy
--- a/images/router/haproxy/reload-haproxy
+++ b/images/router/haproxy/reload-haproxy
@@ -4,23 +4,27 @@ set -o nounset
 
 config_file=/var/lib/haproxy/conf/haproxy.config
 pid_file=/var/lib/haproxy/run/haproxy.pid
-readonly max_wait_time=30
 readonly timeout_opts="-m 1 --connect-timeout 1"
+
+readonly max_wait_time=30
 readonly numeric_re='^[0-9]+$'
+wait_time=${MAX_RELOAD_WAIT_TIME:-$max_wait_time}
+if ! [[ $wait_time =~ $numeric_re ]]; then
+  echo " - Invalid max reload wait time, using default $max_wait_time ..."
+  wait_time=$max_wait_time
+fi
+shutdown_wait_time=${ROUTER_MAX_SHUTDOWN_TIMEOUT:-${wait_time}}
+if ! [[ $shutdown_wait_time =~ $numeric_re ]]; then
+  echo " - Invalid max shutdown wait time, using $wait_time ..."
+  shutdown_wait_time=$wait_time
+fi
 
 function haproxyHealthCheck() {
-  local wait_time=${MAX_RELOAD_WAIT_TIME:-$max_wait_time}
   local port=${ROUTER_SERVICE_HTTP_PORT:-"80"}
   local url="http://localhost:${port}"
   local retries=0
   local start_ts=$(date +"%s")
   local proxy_proto="${ROUTER_USE_PROXY_PROTOCOL-}"
-
-  if ! [[ $wait_time =~ $numeric_re ]]; then
-    echo " - Invalid max reload wait time, using default $max_wait_time ..."
-    wait_time=$max_wait_time
-  fi
-
   local end_ts=$((start_ts + wait_time))
 
   # test with proxy protocol on
@@ -66,6 +70,25 @@ function haproxyHealthCheck() {
 
 
 old_pids=$(pidof haproxy)
+
+# If signaled, stop accepting new connections and drain the current processes
+if [ -n "${ROUTER_SHUTDOWN-}" ]; then
+  echo " - Shutting down"
+  if [ -z "$old_pids" ]; then
+    exit 0
+  fi
+  kill -USR1 $old_pids
+  for i in $( seq 1 $shutdown_wait_time ); do
+    old_pids=$(pidof haproxy)
+    if [ -z "$old_pids" ]; then
+      exit 0
+    fi
+    sleep 1
+  done
+  kill -TERM $old_pids
+  echo "error: Some processes did not exit within ${shutdown_wait_time}s"
+  exit 1
+fi
 
 reload_status=0
 if [ -n "$old_pids" ]; then
